"""tickets

Revision ID: 45004e90f495
Revises: 2f4c71811f37
Create Date: 2026-09-18 19:20:25.934217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45004e90f495'
down_revision: Union[str, Sequence[str], None] = '2f4c71811f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_protocolo', sa.String(length=20), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.Text(length=1000), nullable=False),
    sa.Column('status', sa.Enum('ABERTO', 'EM_ANALISE', 'RESOLVIDO', 'CANCELADO', name='statuschamado', native_enum=False, length=20), nullable=False),
    sa.Column('prioridade', sa.Enum('BAIXA', 'MEDIA', 'ALTA', name='prioridadechamado', native_enum=False, length=20), nullable=True),
    sa.Column('setor', sa.Enum('TI', 'RH', 'FINANCEIRO', 'ADMINISTRATIVO', 'MANUTENCAO', name='setorchamado', native_enum=False, length=20), nullable=False),
    sa.Column('descricao_solucao', sa.Text(length=1000), nullable=True),
    sa.Column('motivo_cancelamento', sa.Text(length=1000), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('solicitante_id', sa.Integer(), nullable=False),
    sa.Column('atendente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atendente_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_protocolo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    # ### end Alembic commands ###
